### ISSUE TITLE
API responds with HTTP 500 in development environment

### ISSUE THREAD

**Issue by kamilmielnik** [michal-marciniec/codeball#89]
After pulling latest code and running `gradlew bootRun`:
Log: http://pastebin.com/mkLEeRpE

After subsequent `gradlew bootRun` there were no errors.
But every endpoint responds with HTTP 500.
Log: http://pastebin.com/dcy4h0sQ

This is what I experience when having this commit checked out: `9c74435ef2756b05bf4b364fea49716c710f7586`

**Comment by michal-marciniec** [comment]
@kamilmielnik fix has just been pushed to master. Sorry for the inconvenience.
