### ISSUE TITLE
Endpoint to end game

### ISSUE THREAD

**Issue by kamilmielnik** [michal-marciniec/codeball#90]
Currently there is no such endpoint.
Suggested endpoint (frontend is ready for it): `PUT` `api/game/{gameId}/end`

App flow:
1. create new game
2. enroll players
3. finish enrollment
4. draw teams
5. end game

---

I have tried PUT-ting `{ isGameOver: true }`, but it causes the game to lose all information.

Request:

```
curl "http://localhost:8080/api/game/4" -X PUT -H "Pragma: no-cache" -H "Origin: http://localhost:8008" -H "Accept-Encoding: gzip, deflate, sdch" -H "Accept-Language: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36" -H "Content-Type: application/json" -H "Accept: */*" -H "Cache-Control: no-cache" -H "Referer: http://localhost:8008/games/upcoming/4" -H "Connection: keep-alive" --data-binary "{""isGameOver"":true}" --compressed
```

Response:

```
{
    "id": 4,
    "startTimestamp": 0,
    "durationInMinutes": 0,
    "teamAScore": 0,
    "teamBScore": 0,
    "pitchId": null,
    "isEnrollmentOver": false,
    "isGameOver": true,
    "enrollments": [],
    "teamAIds": [],
    "teamBIds": []
}
```

**Comment by michal-marciniec** [comment]
@kamilmielnik the requested endpoint has been added. 

Regarding to the issue you mentioned (that game object looses all the information) - PUT requests perform full update of the resource. That means that it will override the existing game with ID 4 will all the information you provided (and if not provided, then defaults will be assigned like zeros and nulls).   Therefore keep in mind that these requests always require full object to be provided (at least we don't support partial updates by now).
